openapi: 3.0.0
info:
  title: FugaFuga
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/fuga/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-fuga-id
components:
  schemas: {}
