openapi: 3.0.0
info:
  title: hogehoge
  version: '1.0'
  contact:
    name: ポケマル
  description: HogeHogeサービス
servers:
  - url: 'http://hogehoge-dev'
    description: develop
  - description: production
    url: 'http://hogehoge-prd'
paths:
  '/users/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: GetUser
      tags:
        - v1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/user.v1.yaml
      operationId: get-users-id
components:
  schemas: {}
  securitySchemes:
    hogehogeKey:
      type: http
      scheme: Bearer
